# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

HestonCOS <- function(S, K, T, r, q, sigma, lmbda, meanV, v0, rho, otype, N) {
    .Call(`_MLEMVD_HestonCOS`, S, K, T, r, q, sigma, lmbda, meanV, v0, rho, otype, N)
}

HestonVega <- function(S, K, T, r, q, sigma, lmbda, meanV, v0, rho, otype, N) {
    .Call(`_MLEMVD_HestonVega`, S, K, T, r, q, sigma, lmbda, meanV, v0, rho, otype, N)
}

getImpliedVolatility <- function(S, V, K, T, r, q, sigma, lmbda, meanV, v0, rho, otype, x_abs_err, max_iter, N) {
    .Call(`_MLEMVD_getImpliedVolatility`, S, V, K, T, r, q, sigma, lmbda, meanV, v0, rho, otype, x_abs_err, max_iter, N)
}

